### ISSUE TITLE
can't find gem jekyll (>= 0.a) with executable jekyll

### ISSUE THREAD

**Issue by yicm** [bazelbuild/bazel-website#272]
ENV:

```bash
$ uname -a
Linux Think 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ gem -v
2.7.6

$ jekyll -v
jekyll 3.6.2

$ bundle -v
Bundler version 1.6.2
```

build info:

```
$ bazel build :site
INFO: Analyzed target //:site (0 packages loaded, 151 targets configured).
INFO: Found 1 target...
ERROR: /home/chengmingyi/workspace/github/bazel-website/BUILD:107:13: Action site-build failed (Exit 1) jekyll failed: error executing command jekyll build -q -s bazel-out/k8-fastbuild/bin/site-srcs -d bazel-out/k8-fastbuild/bin/site-build

Use --sandbox_debug to see verbose messages from the sandbox
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem jekyll (>= 0.a) with executable jekyll (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
        from /home/chengmingyi/gems/bin/jekyll:23:in `<main>'
Target //:site failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.585s, Critical Path: 1.21s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**i have tried to different ruby or jekyll or bundle version. None success.**

**Comment by aiuto** [comment]
I think you need gem 3.2.x or greater. Try updating as per the readme

`sudo apt-get install jekyll ruby-jekyll-paginate ruby-jekyll-sitemap ruby-jekyll-toc ruby-kramdown-parser-gfm
`
